name: Update README with Blog Posts
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install feedparser
      - name: Update README
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📚 Update blog posts"
          git push
      # Add this step to reset config
      - name: Reset local git config
        if: always()  # This ensures it runs even if previous steps fail
        run: |
          git config --local user.email "taylorsabbag@gmail.com"
          git config --local user.name "Taylor Sabbag"